version: '3.1'
services:
  db:
    image: postgres:15.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
    - 5000:5432
    volumes:
    - ./pgdata:/var/lib/postgresql/data
